markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Jonathan Mayhak
url: http://jonathanmayhak.com
description: Just another Jekyll blog
twitter: jmayhak
